#ansible n1 -m file -a "path=home/ec2-user/n1_dir state=directory"
---
- name: update n1 servers
  hosts: n1
   
  tasks:
    - name: Create directory
      file:
        path: /home/ec2-user/new_dir
        state: directory 
...
