---
- name: Deploy ecommerce web App
  hosts: n2
  become: yes
   
  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: host code
      git:
        repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
        dest: /var/www/html/
...
